# Generated by Django 6.0.3 on 2026-04-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(default='EduLibrary Dashboard', max_length=200)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
            ],
        ),
    ]
