# Generated by Django 6.0.3 on 2026-04-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_librarysetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarysetting',
            name='background_image',
        ),
    ]
