# Generated by Django 6.0.3 on 2026-04-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_librarysetting_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarysetting',
            name='issue_days',
            field=models.IntegerField(default=15),
        ),
    ]
